import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import { setI18n } from "@lingui/react/server";
import { LinguiClientProvider } from "../locales/I18nProvider";
import { getI18nInstance } from "../locales/appRouterI18n";
import { Suspense } from "react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const lang = "zh";
  const i18n = getI18nInstance(lang); // get a ready-made i18n instance for the given locale
  setI18n(i18n);
  return (
    <html lang={lang}>
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LinguiClientProvider
          initialLocale={lang}
          initialMessages={i18n.messages}
        >
          <Provider>
            <Suspense fallback={null}>{children}</Suspense>
          </Provider>
        </LinguiClientProvider>
      </body>
    </html>
  );
}
