// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import { LinguiClientProvider } from "../locales/I18nProvider";
import { allMessages, getI18nInstance } from "../locales/appRouterI18n";
import { Suspense } from "react";
import Cookies from "js-cookie";
import { initLingui } from "@/locales/initLingui";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export async function generateMetadata() {
  const lang = Cookies.get("lang") || "zh";
  const i18n = getI18nInstance(lang);
  return {
    title: i18n.t("site.title"),
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const lang = Cookies.get("lang") || "zh";
  initLingui(lang);
  return (
    <html lang={lang}>
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LinguiClientProvider
          initialLocale={lang}
          initialMessages={allMessages[lang]!}
        >
          <Provider>
            <Suspense>{children}</Suspense>
          </Provider>
        </LinguiClientProvider>
      </body>
    </html>
  );
}
